apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment-jenkins
  namespace: BookStore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: BookStore
  template:
    metadata:
      labels:
        app: BookStore
    spec:
      containers:
      - name: OnlineBookStore
        image: jagadeesh/dockerpipeline:1
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: BookStore-service
  namespace: BookStore
spec:
  selector:
    app: BookStore
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000
      nodePort: 32009
      targetPort: 3000
